version: "3"

services:
  frontend:
    image: nginx:1.19
    container_name: frontend_container
    links:
      - backend
    ports:
      - "4500:8080"
    volumes:
      - ./frontend/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/html:/var/www/html
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - com_gen_net

  backend:
    build: ./backend
    volumes:
      - ./backend/flaskapp:/app
    command: uwsgi --ini /app/uwsgi.ini
    container_name: backend_container
    links:
      - database
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - com_gen_net
      
  database:
    image: mysql:5.7
    container_name: database_container
    ports:
      - "13306:13306"
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_TCP_PORT: 13306
      MYSQL_ROOT_PASSWORD: apue145436pue
      MYSQL_DATABASE: mydata
      MYSQL_USER: Mikka
      MYSQL_PASSWORD: apue928476
    networks:
      - com_gen_net

networks:
  com_gen_net:
    driver: bridge

